name: tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests:
    name: ./test.sh
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-latest]
    steps:
    - uses: commaai/timeout@v1
    - uses: actions/checkout@v4
    - run: ./test.sh

  safety_tests:
    name: safety
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        flags: ['', '--ubsan']
    steps:
    - uses: commaai/timeout@v1
    - uses: actions/checkout@v4
    - name: Run safety tests
      run: ./opendbc/safety/tests/test.sh ${{ matrix.flags }}
