name: tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests:
    name: ./test.sh
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-latest]
    steps:
    - uses: commaai/timeout@v1
    - uses: actions/checkout@v4
    - run: ./test.sh

  safety_tests:
    name: safety
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        flags: ['', '--ubsan']
    steps:
    - uses: commaai/timeout@v1
    - uses: actions/checkout@v4
    - name: Run safety tests
      run: ./opendbc/safety/tests/test.sh ${{ matrix.flags }}

  misra_linter:
    name: MISRA C:2012 Linter
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Set up
        run: sudo apt-get install -y --no-install-recommends gcc-arm-none-eabi libnewlib-arm-none-eabi
      - uses: actions/checkout@v4
      - name: Run MISRA C:2012 analysis
        timeout-minutes: 2
        run: cd opendbc/safety/tests/misra && ./test_misra.sh

  misra_mutation:
    name: MISRA C:2012 Mutation
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - name: MISRA mutation tests
        timeout-minutes: 10
        run: |
          source setup.sh
          scons -j8
          cd opendbc/safety/tests/misra
          pytest -s -n8 --randomly-seed $RANDOM test_mutation.py
